version: '2'
services:
  cleanup:
    privileged: true
    image: fjakop/iron-broom:latest
    environment:
      CLEAN_PERIOD: ${CLEAN_PERIOD}
      DECAY_TIME: ${DECAY_TIME}
      DEBUG: ${DEBUG}
      PRETEND: ${PRETEND}
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
